data_dir: /data/tsolis/AI_project/parquet/augmented_with_labels/hourly
batch_size: 1
use_dask: false
save_model: true
save_path: models/poly_selection_model.joblib
log_batch_metrics: true

use_comet: true
comet_project: hcmr-ai
comet_workspace: ioannisgkinis

feature_block:
  base_features: ["vhm0_x", "wspd", "lat", "lon"]
  use_poly: true
  poly_degree: 2
  poly_scope: "all"
  use_selector: true
  selector_type: "elasticnet"
  selector_alpha: 1e-3
  selector_l1_ratio: 0.2
  warmup_days: 7
  use_dimred: false
  dimred_type: "ipca"
  dimred_components: 64
