data_dir: /data/tsolis/AI_project/parquet/augmented_with_labels/hourly
batch_size: 1
use_dask: false
save_model: true
save_path: models/elasticnet_sgd_model.joblib
log_batch_metrics: true

use_comet: true
comet_project: hcmr-ai
comet_workspace: ioannisgkinis

feature_block:
  base_features: ["vhm0_x", "wspd", "lat", "lon"]
  use_poly: false
  poly_degree: 2
  poly_scope: "subset"
  use_selector: true
  selector_type: "elasticnet"
  selector_alpha: 0.05
  selector_l1_ratio: 0.05
  warmup_days: 7
  use_dimred: false
  dimred_type: "ipca"
  dimred_components: 64
